import { isNull, sql } from "drizzle-orm";
import { boolean, check, customType, date, index, integer, jsonb, pgPolicy, pgRole, pgTable, primaryKey, text, timestamp, unique, uniqueIndex, uuid } from "drizzle-orm/pg-core";

// Tenant isolation: every tenant table carries company_id and a policy that
// only matches rows of the company set by withTenant(). Unset => no rows.
// nullif: a pooled connection that once had it set reports '' rather than NULL.
const currentCompany = sql`nullif(current_setting('app.company_id', true), '')::uuid`;
const tenantPolicy = (column: string) =>
  pgPolicy("tenant_isolation", {
    for: "all",
    to: "public",
    using: sql`${sql.identifier(column)} = ${currentCompany}`,
    withCheck: sql`${sql.identifier(column)} = ${currentCompany}`,
  });

// Better Auth's role (src/lib/auth.ts). Sign-in looks users up by email before
// any company is known, so it gets an unscoped policy on the tables it needs.
const authRole = pgRole("notifyhub_auth").existing();
const authPolicy = pgPolicy("auth_unscoped", { for: "all", to: authRole, using: sql`true`, withCheck: sql`true` });

const ts = () => timestamp({ withTimezone: true });

export const companies = pgTable(
  "companies",
  {
    id: uuid().primaryKey().defaultRandom(),
    name: text().notNull(),
    domain: text().notNull().unique(),
    timeZone: text().notNull(),
    // Local time of day for daily task follow-ups (PRD 5.8), in timeZone.
    followUpTime: text().notNull().default("09:00"),
    // PRD 9.1: everyone must set up 2FA before using the app (requireMember).
    requireTwoFactor: boolean().notNull().default(false),
    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    tenantPolicy("id"),
    authPolicy,
    check("companies_follow_up_time_valid", sql`${t.followUpTime} ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'`),
  ],
).enableRLS();

export const departments = pgTable(
  "departments",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    name: text().notNull(),
    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique().on(t.companyId, t.name), tenantPolicy("company_id")],
).enableRLS();

// --- Better Auth tables. Generated by `npx auth generate`, then edited:
// timestamptz, company_id is a uuid FK, and RLS on user. Keep field names in
// sync with Better Auth if regenerating.

export const user = pgTable(
  "user",
  {
    id: text().primaryKey(),
    name: text().notNull(),
    email: text().notNull().unique(),
    emailVerified: boolean().default(false).notNull(),
    image: text(),
    createdAt: ts().defaultNow().notNull(),
    updatedAt: ts()
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
    companyId: uuid().references(() => companies.id),
    // Set = deactivated: no sign-in (Better Auth session hook), sessions deleted.
    deactivatedAt: ts(),
    // Better Auth twoFactor plugin.
    twoFactorEnabled: boolean().default(false),
    // The person's own zone for display; null = the company's.
    timeZone: text(),
  },
  (t) => [index().on(t.companyId), tenantPolicy("company_id"), authPolicy],
).enableRLS();

// session, account and verification hold tokens and password hashes. Only
// notifyhub_auth is granted them (migration 0003); notifyhub_app is not.
export const session = pgTable(
  "session",
  {
    id: text().primaryKey(),
    expiresAt: ts().notNull(),
    token: text().notNull().unique(),
    createdAt: ts().defaultNow().notNull(),
    updatedAt: ts()
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text(),
    userAgent: text(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (t) => [index().on(t.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text().primaryKey(),
    accountId: text().notNull(),
    providerId: text().notNull(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text(),
    refreshToken: text(),
    idToken: text(),
    accessTokenExpiresAt: ts(),
    refreshTokenExpiresAt: ts(),
    scope: text(),
    password: text(),
    createdAt: ts().defaultNow().notNull(),
    updatedAt: ts()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index().on(t.userId)],
);

// Better Auth twoFactor plugin (field names must match it). The secret and
// backup codes are encrypted by Better Auth. Like session/account, only
// notifyhub_auth is granted this table (migration 0022).
export const twoFactor = pgTable(
  "two_factor",
  {
    id: text().primaryKey(),
    secret: text().notNull(),
    backupCodes: text().notNull(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    verified: boolean().default(true),
    failedVerificationCount: integer().default(0),
    lockedUntil: ts(),
  },
  (t) => [index().on(t.secret), index().on(t.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text().primaryKey(),
    identifier: text().notNull(),
    value: text().notNull(),
    expiresAt: ts().notNull(),
    createdAt: ts().defaultNow().notNull(),
    updatedAt: ts()
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index().on(t.identifier)],
);

// --- Roles and permissions (PRD 2.1). The permission catalogue is code:
// src/lib/permissions.ts.

// company_id NULL = system role: readable by every company, writable by none
// through the app role (the tenant policy's WITH CHECK never matches NULL).
export const roles = pgTable(
  "roles",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid().references(() => companies.id),
    name: text().notNull(),
    permissions: text().array().notNull(),
    createdAt: ts().notNull().defaultNow(),
  },
  (t) => [
    unique().on(t.companyId, t.name),
    tenantPolicy("company_id"),
    pgPolicy("system_roles_readable", { for: "select", to: "public", using: sql`company_id is null` }),
  ],
).enableRLS();

export const userRoles = pgTable(
  "user_roles",
  {
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    roleId: uuid()
      .notNull()
      .references(() => roles.id, { onDelete: "cascade" }),
  },
  // authPolicy: onboarding makes the company's creator admin in its transaction.
  (t) => [primaryKey({ columns: [t.userId, t.roleId] }), tenantPolicy("company_id"), authPolicy],
).enableRLS();

export const departmentMembers = pgTable(
  "department_members",
  {
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    departmentId: uuid()
      .notNull()
      .references(() => departments.id, { onDelete: "cascade" }),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    isManager: boolean().notNull().default(false),
  },
  // authPolicy: accepting an invite adds the new user to its departments.
  (t) => [primaryKey({ columns: [t.departmentId, t.userId] }), index().on(t.userId), tenantPolicy("company_id"), authPolicy],
).enableRLS();

// Only the SHA-256 of the emailed token is stored. authPolicy: the accept page
// looks an invite up by token before any company is known.
export const invitations = pgTable(
  "invitations",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    email: text().notNull(),
    roleIds: uuid().array().notNull(),
    departmentIds: uuid().array().notNull().default(sql`'{}'`),
    invitedBy: text()
      .notNull()
      .references(() => user.id),
    tokenHash: text().notNull().unique(),
    expiresAt: ts().notNull(),
    acceptedAt: ts(),
    createdAt: ts().notNull().defaultNow(),
  },
  (t) => [
    // One pending invite per email per company; re-inviting replaces it.
    uniqueIndex().on(t.companyId, t.email).where(isNull(t.acceptedAt)),
    tenantPolicy("company_id"),
    authPolicy,
  ],
).enableRLS();

// --- Reminders (PRD 5). Targets are what the creator picked; they're resolved
// to actual recipients at send time (src/lib/reminders.ts resolveRecipients).

export const REMINDER_STATUSES = ["pending_approval", "rejected", "scheduled", "paused", "sending", "sent", "cancelled"] as const;
export type ReminderStatus = (typeof REMINDER_STATUSES)[number];

export const reminders = pgTable(
  "reminders",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    shortId: text().notNull().unique(),
    createdBy: text()
      .notNull()
      .references(() => user.id),
    title: text().notNull(),
    description: text().notNull().default(""),
    links: jsonb().$type<{ label: string; url: string }[]>().notNull().default([]),
    senderName: text().notNull(),
    // The next occurrence (for a one-time reminder, its only one).
    sendAt: ts().notNull(),
    // "Send now" on a repeating reminder: the worker sends one extra occurrence
    // at this instant and clears it; sendAt (the schedule) is untouched.
    sendNowAt: ts(),
    // Null = one-time. Occurrences are computed from anchorLocal in timeZone
    // (src/lib/recurrence.ts); the zone is copied from the company at create.
    recurrence: jsonb().$type<import("@/lib/recurrence").Rule>(),
    timeZone: text().notNull(),
    anchorLocal: text().notNull(),
    // A task: every internal recipient marks it done (deliveries.done_at).
    // Each occurrence is due this long after it's sent.
    isTask: boolean().notNull().default(false),
    // Delivery channels (PRD 5.3): email and/or slack.
    channels: text().array().$type<("email" | "slack")[]>().notNull().default(sql`'{email}'`),
    dueAfterMinutes: integer(),
    // Free-form labels for filtering (PRD 5.1): lowercase, validated in validateInput.
    tags: text().array().notNull().default(sql`'{}'`),
    status: text().$type<ReminderStatus>().notNull(),
    decidedBy: text().references(() => user.id),
    decidedAt: ts(),
    rejectionReason: text(),
    createdAt: ts().notNull().defaultNow(),
    updatedAt: ts()
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index().on(t.status, t.sendAt),
    index("reminders_send_now_idx").on(t.sendNowAt).where(sql`${t.sendNowAt} is not null`),
    index("reminders_tags_idx").using("gin", t.tags),
    check("reminders_task_due", sql`not ${t.isTask} or ${t.dueAfterMinutes} > 0`),
    check("reminders_channels_valid", sql`cardinality(${t.channels}) > 0 and ${t.channels} <@ array['email','slack']`),
    check("reminders_status_valid", sql`${t.status} in ('pending_approval','rejected','scheduled','paused','sending','sent','cancelled')`),
    tenantPolicy("company_id"),
  ],
).enableRLS();

export const reminderTargets = pgTable(
  "reminder_targets",
  {
    reminderId: uuid()
      .notNull()
      .references(() => reminders.id, { onDelete: "cascade" }),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    kind: text().$type<"user" | "department" | "group" | "company" | "email" | "slack_channel">().notNull(),
    // user, department or group id, email, or Slack channel id; null for kind = company.
    ref: text(),
    // Display name at pick time (Slack channel name), so the page needn't call Slack.
    label: text(),
  },
  (t) => [
    index().on(t.reminderId),
    check("reminder_targets_kind_valid", sql`${t.kind} in ('user','department','group','company','email','slack_channel')`),
    tenantPolicy("company_id"),
  ],
).enableRLS();

// One row per time a reminder goes out. unique(reminder_id, occurs_at): an
// occurrence is created once. skipped = the user skipped it; missed = the
// worker was down and a later occurrence was sent instead (catch-up = latest only).
export const reminderOccurrences = pgTable(
  "reminder_occurrences",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    reminderId: uuid()
      .notNull()
      .references(() => reminders.id, { onDelete: "cascade" }),
    occursAt: ts().notNull(),
    status: text().$type<"sending" | "sent" | "skipped" | "missed">().notNull(),
    dueAt: ts(), // tasks only
    createdAt: ts().notNull().defaultNow(),
  },
  (t) => [
    unique().on(t.reminderId, t.occursAt),
    check("reminder_occurrences_status_valid", sql`${t.status} in ('sending','sent','skipped','missed')`),
    tenantPolicy("company_id"),
  ],
).enableRLS();

// One row per (occurrence, recipient email): the unique key is what makes a
// second send of the same occurrence to the same person impossible. Written by
// the worker (owner connection); read by the web for the delivery log.
export const deliveries = pgTable(
  "deliveries",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    reminderId: uuid()
      .notNull()
      .references(() => reminders.id, { onDelete: "cascade" }),
    occurrenceId: uuid()
      .notNull()
      .references(() => reminderOccurrences.id, { onDelete: "cascade" }),
    channel: text().$type<"email" | "slack">().notNull().default("email"),
    // email: the address. slack: a channel id (C…) or, for a DM, the internal
    // user id (the Slack user id is looked up at send time).
    address: text().notNull(),
    userId: text().references(() => user.id, { onDelete: "set null" }),
    status: text().$type<"queued" | "sending" | "sent" | "failed">().notNull().default("queued"),
    attempts: integer().notNull().default(0),
    lastError: text(),
    sentAt: ts(),
    // The posted Slack message, so Phase B can update it (Mark done / Snooze).
    slackChannel: text(),
    slackTs: text(),
    updatedAt: ts()
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
    createdAt: ts().notNull().defaultNow(),
  },
  (t) => [
    unique().on(t.occurrenceId, t.channel, t.address),
    check("deliveries_channel_valid", sql`${t.channel} in ('email','slack')`),
    index().on(t.reminderId),
    index().on(t.status, t.updatedAt),
    check("deliveries_status_valid", sql`${t.status} in ('queued','sending','sent','failed')`),
    tenantPolicy("company_id"),
  ],
).enableRLS();

// A task's assignees: one row per (occurrence, internal user), whatever
// channels it went out on (one person can have an email and a Slack delivery
// for the same occurrence). Completion and follow-ups live here.
// last_followup_on (company-local date) is the once-a-day follow-up claim.
export const taskAssignments = pgTable(
  "task_assignments",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    reminderId: uuid()
      .notNull()
      .references(() => reminders.id, { onDelete: "cascade" }),
    occurrenceId: uuid()
      .notNull()
      .references(() => reminderOccurrences.id, { onDelete: "cascade" }),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    doneAt: ts(),
    followups: integer().notNull().default(0),
    lastFollowupOn: date({ mode: "string" }),
    // Slack "Snooze": the worker re-sends the DM once this passes (then clears it).
    snoozedUntil: ts(),
    createdAt: ts().notNull().defaultNow(),
  },
  (t) => [unique().on(t.occurrenceId, t.userId), index().on(t.userId), tenantPolicy("company_id")],
).enableRLS();

// One Slack workspace per company (PRD 7.2). The bot token is AES-GCM
// encrypted (src/lib/crypto.ts) and never leaves the server.
export const slackInstallations = pgTable(
  "slack_installations",
  {
    companyId: uuid()
      .primaryKey()
      .references(() => companies.id),
    // A workspace belongs to one company.
    teamId: text().notNull().unique(),
    teamName: text().notNull(),
    botTokenEnc: text().notNull(),
    botUserId: text().notNull(),
    fallbackChannelId: text(),
    fallbackChannelName: text(),
    // Granted bot scopes (from oauth.v2.access), e.g. to tell whether files:write is there.
    scopes: text().array().notNull().default(sql`'{}'`),
    installedBy: text().references(() => user.id, { onDelete: "set null" }),
    // Daily digest (PRD 7.2): overdue tasks + the next 24h, at digestTime in
    // the company zone, to these channels and people. last_digest_on is the
    // once-a-day claim (company-local date).
    digestEnabled: boolean().notNull().default(false),
    digestTime: text().notNull().default("09:00"),
    digestChannelIds: text().array().notNull().default(sql`'{}'`),
    digestUserIds: text().array().notNull().default(sql`'{}'`),
    lastDigestOn: date({ mode: "string" }),
    createdAt: ts().notNull().defaultNow(),
  },
  // authPolicy: a Slack button click names a workspace (team_id), not a
  // company; the interactions endpoint finds the company through authDb.
  (t) => [
    tenantPolicy("company_id"),
    authPolicy,
    check("slack_digest_time_valid", sql`${t.digestTime} ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'`),
  ],
).enableRLS();

// --- Attachments (PRD 5.7) ---------------------------------------------------------
// Files live in Postgres (decided with the user): metadata here, bytes in
// attachment_blobs so listing never loads file contents. Only
// src/lib/storage.ts touches the blobs (the seam for a later move to S3).

const bytea = customType<{ data: Buffer }>({ dataType: () => "bytea" });

export const attachments = pgTable(
  "attachments",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    reminderId: uuid()
      .notNull()
      .references(() => reminders.id, { onDelete: "cascade" }),
    fileName: text().notNull(),
    // From the sniffed content, not the uploader's claim (src/lib/attachments.ts).
    contentType: text().notNull(),
    size: integer().notNull(),
    sha256: text().notNull(),
    uploadedBy: text().references(() => user.id, { onDelete: "set null" }),
    createdAt: ts().notNull().defaultNow(),
  },
  (t) => [index().on(t.reminderId), tenantPolicy("company_id")],
).enableRLS();

export const attachmentBlobs = pgTable(
  "attachment_blobs",
  {
    attachmentId: uuid()
      .primaryKey()
      .references(() => attachments.id, { onDelete: "cascade" }),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    data: bytea().notNull(),
  },
  () => [tenantPolicy("company_id")],
).enableRLS();

// --- Comments (PRD 5.11) -----------------------------------------------------------
// One level of threading: parent_id is null (top level) or a top-level comment.
// Deleted comments keep their row (body cleared) so replies keep context.
export const comments = pgTable(
  "comments",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    reminderId: uuid()
      .notNull()
      .references(() => reminders.id, { onDelete: "cascade" }),
    authorId: text().references(() => user.id, { onDelete: "set null" }),
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    parentId: uuid().references((): any => comments.id, { onDelete: "cascade" }),
    body: text().notNull(),
    createdAt: ts().notNull().defaultNow(),
    editedAt: ts(),
    deletedAt: ts(),
    deletedBy: text().references(() => user.id, { onDelete: "set null" }),
  },
  (t) => [index().on(t.reminderId, t.createdAt), tenantPolicy("company_id")],
).enableRLS();

// Who a comment mentions: explicit ids picked in the composer, not parsed text.
export const commentMentions = pgTable(
  "comment_mentions",
  {
    commentId: uuid()
      .notNull()
      .references(() => comments.id, { onDelete: "cascade" }),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.commentId, t.userId] }), tenantPolicy("company_id")],
).enableRLS();

// In-app notification centre (PRD 7.5). One row per person per event, written
// when the event happens. dedupe_key makes repeatable events (worker retries,
// undo/redo) insert once.
export const notifications = pgTable(
  "notifications",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    kind: text().notNull(),
    reminderId: uuid().references(() => reminders.id, { onDelete: "cascade" }),
    commentId: uuid().references(() => comments.id, { onDelete: "cascade" }),
    actorId: text().references(() => user.id, { onDelete: "set null" }),
    text: text().notNull(),
    dedupeKey: text(),
    createdAt: ts().notNull().defaultNow(),
    readAt: ts(),
  },
  (t) => [
    index().on(t.userId, t.createdAt.desc()),
    index("notifications_unread_idx").on(t.userId).where(isNull(t.readAt)),
    uniqueIndex().on(t.userId, t.dedupeKey),
    check(
      "notifications_kind_valid",
      sql`${t.kind} in ('reminder','task','approval','mention','comment','decided','tasks_done','failed')`,
    ),
    tenantPolicy("company_id"),
  ],
).enableRLS();

// Opt-outs: a row turns one event off on one channel. No row = on.
export const notificationMutes = pgTable(
  "notification_mutes",
  {
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    event: text().notNull(),
    channel: text().notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.event, t.channel] }), tenantPolicy("company_id")],
).enableRLS();

// Custom distribution lists (PRD 4). Anyone with groups.create makes one; the
// creator or groups.manage edits it. Resolved to members at send time.
export const groups = pgTable(
  "groups",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    name: text().notNull(),
    createdBy: text().references(() => user.id, { onDelete: "set null" }),
    createdAt: ts().notNull().defaultNow(),
  },
  (t) => [uniqueIndex("groups_company_name_idx").on(t.companyId, sql`lower(${t.name})`), tenantPolicy("company_id")],
).enableRLS();

export const groupMembers = pgTable(
  "group_members",
  {
    groupId: uuid()
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.groupId, t.userId] }), index().on(t.userId), tenantPolicy("company_id")],
).enableRLS();
