import { isNull, sql } from "drizzle-orm";
import { boolean, check, index, integer, jsonb, pgPolicy, pgRole, pgTable, primaryKey, text, timestamp, unique, uniqueIndex, uuid } from "drizzle-orm/pg-core";

// Tenant isolation: every tenant table carries company_id and a policy that
// only matches rows of the company set by withTenant(). Unset => no rows.
// nullif: a pooled connection that once had it set reports '' rather than NULL.
const currentCompany = sql`nullif(current_setting('app.company_id', true), '')::uuid`;
const tenantPolicy = (column: string) =>
  pgPolicy("tenant_isolation", {
    for: "all",
    to: "public",
    using: sql`${sql.identifier(column)} = ${currentCompany}`,
    withCheck: sql`${sql.identifier(column)} = ${currentCompany}`,
  });

// Better Auth's role (src/lib/auth.ts). Sign-in looks users up by email before
// any company is known, so it gets an unscoped policy on the tables it needs.
const authRole = pgRole("notifyhub_auth").existing();
const authPolicy = pgPolicy("auth_unscoped", { for: "all", to: authRole, using: sql`true`, withCheck: sql`true` });

const ts = () => timestamp({ withTimezone: true });

export const companies = pgTable(
  "companies",
  {
    id: uuid().primaryKey().defaultRandom(),
    name: text().notNull(),
    domain: text().notNull().unique(),
    timeZone: text().notNull(),
    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  () => [tenantPolicy("id"), authPolicy],
).enableRLS();

export const departments = pgTable(
  "departments",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    name: text().notNull(),
    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique().on(t.companyId, t.name), tenantPolicy("company_id")],
).enableRLS();

// --- Better Auth tables. Generated by `npx auth generate`, then edited:
// timestamptz, company_id is a uuid FK, and RLS on user. Keep field names in
// sync with Better Auth if regenerating.

export const user = pgTable(
  "user",
  {
    id: text().primaryKey(),
    name: text().notNull(),
    email: text().notNull().unique(),
    emailVerified: boolean().default(false).notNull(),
    image: text(),
    createdAt: ts().defaultNow().notNull(),
    updatedAt: ts()
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
    companyId: uuid().references(() => companies.id),
    // Set = deactivated: no sign-in (Better Auth session hook), sessions deleted.
    deactivatedAt: ts(),
  },
  (t) => [index().on(t.companyId), tenantPolicy("company_id"), authPolicy],
).enableRLS();

// session, account and verification hold tokens and password hashes. Only
// notifyhub_auth is granted them (migration 0003); notifyhub_app is not.
export const session = pgTable(
  "session",
  {
    id: text().primaryKey(),
    expiresAt: ts().notNull(),
    token: text().notNull().unique(),
    createdAt: ts().defaultNow().notNull(),
    updatedAt: ts()
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text(),
    userAgent: text(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (t) => [index().on(t.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text().primaryKey(),
    accountId: text().notNull(),
    providerId: text().notNull(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text(),
    refreshToken: text(),
    idToken: text(),
    accessTokenExpiresAt: ts(),
    refreshTokenExpiresAt: ts(),
    scope: text(),
    password: text(),
    createdAt: ts().defaultNow().notNull(),
    updatedAt: ts()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index().on(t.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text().primaryKey(),
    identifier: text().notNull(),
    value: text().notNull(),
    expiresAt: ts().notNull(),
    createdAt: ts().defaultNow().notNull(),
    updatedAt: ts()
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index().on(t.identifier)],
);

// --- Roles and permissions (PRD 2.1). The permission catalogue is code:
// src/lib/permissions.ts.

// company_id NULL = system role: readable by every company, writable by none
// through the app role (the tenant policy's WITH CHECK never matches NULL).
export const roles = pgTable(
  "roles",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid().references(() => companies.id),
    name: text().notNull(),
    permissions: text().array().notNull(),
    createdAt: ts().notNull().defaultNow(),
  },
  (t) => [
    unique().on(t.companyId, t.name),
    tenantPolicy("company_id"),
    pgPolicy("system_roles_readable", { for: "select", to: "public", using: sql`company_id is null` }),
  ],
).enableRLS();

export const userRoles = pgTable(
  "user_roles",
  {
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    roleId: uuid()
      .notNull()
      .references(() => roles.id, { onDelete: "cascade" }),
  },
  // authPolicy: onboarding makes the company's creator admin in its transaction.
  (t) => [primaryKey({ columns: [t.userId, t.roleId] }), tenantPolicy("company_id"), authPolicy],
).enableRLS();

export const departmentMembers = pgTable(
  "department_members",
  {
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    departmentId: uuid()
      .notNull()
      .references(() => departments.id, { onDelete: "cascade" }),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    isManager: boolean().notNull().default(false),
  },
  // authPolicy: accepting an invite adds the new user to its departments.
  (t) => [primaryKey({ columns: [t.departmentId, t.userId] }), index().on(t.userId), tenantPolicy("company_id"), authPolicy],
).enableRLS();

// Only the SHA-256 of the emailed token is stored. authPolicy: the accept page
// looks an invite up by token before any company is known.
export const invitations = pgTable(
  "invitations",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    email: text().notNull(),
    roleIds: uuid().array().notNull(),
    departmentIds: uuid().array().notNull().default(sql`'{}'`),
    invitedBy: text()
      .notNull()
      .references(() => user.id),
    tokenHash: text().notNull().unique(),
    expiresAt: ts().notNull(),
    acceptedAt: ts(),
    createdAt: ts().notNull().defaultNow(),
  },
  (t) => [
    // One pending invite per email per company; re-inviting replaces it.
    uniqueIndex().on(t.companyId, t.email).where(isNull(t.acceptedAt)),
    tenantPolicy("company_id"),
    authPolicy,
  ],
).enableRLS();

// --- Reminders (PRD 5). Targets are what the creator picked; they're resolved
// to actual recipients at send time (src/lib/reminders.ts resolveRecipients).

export const REMINDER_STATUSES = ["pending_approval", "rejected", "scheduled", "paused", "sending", "sent", "cancelled"] as const;
export type ReminderStatus = (typeof REMINDER_STATUSES)[number];

export const reminders = pgTable(
  "reminders",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    shortId: text().notNull().unique(),
    createdBy: text()
      .notNull()
      .references(() => user.id),
    title: text().notNull(),
    description: text().notNull().default(""),
    links: jsonb().$type<{ label: string; url: string }[]>().notNull().default([]),
    senderName: text().notNull(),
    // The next occurrence (for a one-time reminder, its only one).
    sendAt: ts().notNull(),
    // Null = one-time. Occurrences are computed from anchorLocal in timeZone
    // (src/lib/recurrence.ts); the zone is copied from the company at create.
    recurrence: jsonb().$type<import("@/lib/recurrence").Rule>(),
    timeZone: text().notNull(),
    anchorLocal: text().notNull(),
    status: text().$type<ReminderStatus>().notNull(),
    decidedBy: text().references(() => user.id),
    decidedAt: ts(),
    rejectionReason: text(),
    createdAt: ts().notNull().defaultNow(),
    updatedAt: ts()
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index().on(t.status, t.sendAt),
    check("reminders_status_valid", sql`${t.status} in ('pending_approval','rejected','scheduled','paused','sending','sent','cancelled')`),
    tenantPolicy("company_id"),
  ],
).enableRLS();

export const reminderTargets = pgTable(
  "reminder_targets",
  {
    reminderId: uuid()
      .notNull()
      .references(() => reminders.id, { onDelete: "cascade" }),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    kind: text().$type<"user" | "department" | "company" | "email">().notNull(),
    // user id, department id, or email; null for kind = company.
    ref: text(),
  },
  (t) => [
    index().on(t.reminderId),
    check("reminder_targets_kind_valid", sql`${t.kind} in ('user','department','company','email')`),
    tenantPolicy("company_id"),
  ],
).enableRLS();

// One row per time a reminder goes out. unique(reminder_id, occurs_at): an
// occurrence is created once. skipped = the user skipped it; missed = the
// worker was down and a later occurrence was sent instead (catch-up = latest only).
export const reminderOccurrences = pgTable(
  "reminder_occurrences",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    reminderId: uuid()
      .notNull()
      .references(() => reminders.id, { onDelete: "cascade" }),
    occursAt: ts().notNull(),
    status: text().$type<"sending" | "sent" | "skipped" | "missed">().notNull(),
    createdAt: ts().notNull().defaultNow(),
  },
  (t) => [
    unique().on(t.reminderId, t.occursAt),
    check("reminder_occurrences_status_valid", sql`${t.status} in ('sending','sent','skipped','missed')`),
    tenantPolicy("company_id"),
  ],
).enableRLS();

// One row per (occurrence, recipient email): the unique key is what makes a
// second send of the same occurrence to the same person impossible. Written by
// the worker (owner connection); read by the web for the delivery log.
export const deliveries = pgTable(
  "deliveries",
  {
    id: uuid().primaryKey().defaultRandom(),
    companyId: uuid()
      .notNull()
      .references(() => companies.id),
    reminderId: uuid()
      .notNull()
      .references(() => reminders.id, { onDelete: "cascade" }),
    occurrenceId: uuid()
      .notNull()
      .references(() => reminderOccurrences.id, { onDelete: "cascade" }),
    email: text().notNull(),
    userId: text().references(() => user.id, { onDelete: "set null" }),
    status: text().$type<"queued" | "sending" | "sent" | "failed">().notNull().default("queued"),
    attempts: integer().notNull().default(0),
    lastError: text(),
    sentAt: ts(),
    updatedAt: ts()
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
    createdAt: ts().notNull().defaultNow(),
  },
  (t) => [
    unique().on(t.occurrenceId, t.email),
    index().on(t.reminderId),
    index().on(t.status, t.updatedAt),
    check("deliveries_status_valid", sql`${t.status} in ('queued','sending','sent','failed')`),
    tenantPolicy("company_id"),
  ],
).enableRLS();
